name: "CI"

on:
  pull_request: # Triggered on pull requests to any branch
  push:
    branches: # Additionally, trigger on push events to specific branches
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Fetching JWST data
    defaults:
      run:
        working-directory: 'JWST'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
        cache: "pip"

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python3 -m venv env
        source ./env/bin/activate 
        python -m pip install --upgrade --user pip
        pip install --user -r requirements.txt

    - name: Run fetcher
      run: | 
        python apply_pipeline.py